### ISSUE TITLE
broken `yarn exec ...` with `Skipped due to mode=update-lockfile`

### ISSUE THREAD

**Issue by trim21** [mhassan1/yarn-plugin-after-install#11]
I have a config `nodeLinker: node-modules
` with hook `yarn exec husky install` to instal husky git hooks

But `--mode=update-lockfile` won't install packages and doesn't link bin.

Is there anyway to bypass this?

```
yarn install --mode=update-lockfile
```

```text
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 475ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 22 packages were already cached, 2 had to be fetched
➤ YN0000: └ Completed in 4s 251ms
➤ YN0000: ┌ Link step
➤ YN0073: │ Skipped due to mode=update-lockfile
➤ YN0000: └ Completed
Running `afterInstall` hook...
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)

$ yarn exec <commandName> ...
➤ YN0001: Error: The `afterInstall` hook failed, see output above.
    at afterAllInstalled (/mnt/renovate/gh/trim21/gm-fetch/.yarn/plugins/@yarnpkg/plugin-after-install.cjs:6:1476)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Ka.triggerHook (/home/ubuntu/.cache/node/corepack/yarn/3.5.1/yarn.js:392:3295)
    at async je.install (/home/ubuntu/.cache/node/corepack/yarn/3.5.1/yarn.js:442:4457)
    at async /home/ubuntu/.cache/node/corepack/yarn/3.5.1/yarn.js:499:12044
    at async Ge.start (/home/ubuntu/.cache/node/corepack/yarn/3.5.1/yarn.js:409:2387)
    at async yu.execute (/home/ubuntu/.cache/node/corepack/yarn/3.5.1/yarn.js:499:11944)
    at async yu.validateAndExecute (/home/ubuntu/.cache/node/corepack/yarn/3.5.1/yarn.js:345:664)
    at async Hn.run (/home/ubuntu/.cache/node/corepack/yarn/3.5.1/yarn.js:359:2057)
    at async Hn.runExit (/home/ubuntu/.cache/node/corepack/yarn/3.5.1/yarn.js:359:2241)
➤ YN0000: Failed with errors in 5s 762ms
```

**Comment by mhassan1** [comment]
It seems like the overwhelming use case for `afterInstall` is to run a script after an install runs, but one could argue that `--mode=update-lockfile` is not really an install, since it doesn't install anything.

I think it would make sense to skip the `afterInstall` script for `--mode=update-lockfile`.

**Comment by trim21** [comment]
Thank you very much! this is really useful
